MOCK_USERS = [
    {
        "frontend_id": "usr-001",
        "name": "Ana Silva",
        "email": "ana.silva@mailerweb.com",
        "role": "admin",
        "is_active": True,
    },
    {
        "frontend_id": "usr-002",
        "name": "Bruno Lima",
        "email": "bruno.lima@mailerweb.com",
        "role": "user",
        "is_active": True,
    },
    {
        "frontend_id": "usr-003",
        "name": "Carla Rocha",
        "email": "carla.rocha@mailerweb.com",
        "role": "user",
        "is_active": True,
    },
    {
        "frontend_id": "usr-004",
        "name": "Diego Moura",
        "email": "diego.moura@mailerweb.com",
        "role": "user",
        "is_active": True,
    },
    {
        "frontend_id": "usr-005",
        "name": "Marina Costa",
        "email": "marina.costa@mailerweb.com",
        "role": "user",
        "is_active": True,
    },
]

MOCK_ROOMS = [
    {"frontend_id": "room-aurora", "name": "Sala Aurora", "capacity": 6},
    {"frontend_id": "room-atlas", "name": "Sala Atlas", "capacity": 10},
    {"frontend_id": "room-rio", "name": "Sala Rio", "capacity": 4},
    {"frontend_id": "room-nexus", "name": "Sala Nexus", "capacity": 16},
]

MOCK_BOOKINGS = [
    {
        "frontend_id": "booking-001",
        "title": "Daily Produto",
        "room_frontend_id": "room-aurora",
        "created_by_frontend_id": "usr-001",
        "start_at": "2026-04-16T09:00",
        "end_at": "2026-04-16T09:30",
        "status": "active",
        "participants": ["ana.silva@mailerweb.com", "bruno.lima@mailerweb.com"],
    },
    {
        "frontend_id": "booking-002",
        "title": "Planejamento Sprint",
        "room_frontend_id": "room-atlas",
        "created_by_frontend_id": "usr-003",
        "start_at": "2026-04-16T10:00",
        "end_at": "2026-04-16T11:30",
        "status": "active",
        "participants": [
            "ana.silva@mailerweb.com",
            "carla.rocha@mailerweb.com",
            "diego.moura@mailerweb.com",
        ],
    },
    {
        "frontend_id": "booking-003",
        "title": "Entrevista Engenharia",
        "room_frontend_id": "room-rio",
        "created_by_frontend_id": "usr-002",
        "start_at": "2026-04-16T14:00",
        "end_at": "2026-04-16T15:00",
        "status": "cancelled",
        "participants": ["people@mailerweb.com", "candidato@example.com"],
    },
    {
        "frontend_id": "booking-004",
        "title": "Revisao de Campanha",
        "room_frontend_id": "room-nexus",
        "created_by_frontend_id": "usr-005",
        "start_at": "2026-04-16T15:30",
        "end_at": "2026-04-16T16:30",
        "status": "active",
        "participants": [
            "marina.costa@mailerweb.com",
            "ana.silva@mailerweb.com",
            "bruno.lima@mailerweb.com",
        ],
    },
    {
        "frontend_id": "booking-005",
        "title": "1:1 Lideranca",
        "room_frontend_id": "room-rio",
        "created_by_frontend_id": "usr-001",
        "start_at": "2026-04-17T11:00",
        "end_at": "2026-04-17T11:45",
        "status": "active",
        "participants": ["ana.silva@mailerweb.com", "diego.moura@mailerweb.com"],
    },
    {
        "frontend_id": "booking-006",
        "title": "Retrospectiva Produto",
        "room_frontend_id": "room-aurora",
        "created_by_frontend_id": "usr-001",
        "start_at": "2026-04-17T09:00",
        "end_at": "2026-04-17T10:00",
        "status": "cancelled",
        "participants": [
            "ana.silva@mailerweb.com",
            "bruno.lima@mailerweb.com",
            "carla.rocha@mailerweb.com",
        ],
    },
    {
        "frontend_id": "booking-007",
        "title": "Alinhamento Financeiro",
        "room_frontend_id": "room-atlas",
        "created_by_frontend_id": "usr-004",
        "start_at": "2026-04-17T13:30",
        "end_at": "2026-04-17T14:30",
        "status": "cancelled",
        "participants": [
            "diego.moura@mailerweb.com",
            "carla.rocha@mailerweb.com",
            "financeiro@mailerweb.com",
        ],
    },
]
